// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcN-tclnWky9EZsT5iWGg_J5sc0R6mc7o',
    appId: '1:1087599431089:android:b0e11dbcd863dd20d40190',
    messagingSenderId: '1087599431089',
    projectId: 'esp32cam-461c5',
    databaseURL: 'https://esp32cam-461c5-default-rtdb.firebaseio.com',
    storageBucket: 'esp32cam-461c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6Z_dONHDZgHw5GagtGp7hM8HtnuMHkQ',
    appId: '1:1087599431089:ios:0afb4e67c6f92fd7d40190',
    messagingSenderId: '1087599431089',
    projectId: 'esp32cam-461c5',
    databaseURL: 'https://esp32cam-461c5-default-rtdb.firebaseio.com',
    storageBucket: 'esp32cam-461c5.appspot.com',
    iosClientId: '1087599431089-mgumb69sctmffn31mmbedg6ruj29rqh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlueApp',
  );
}
